name: equi7grid_env
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - gdal
  - pyproj
  - pip
  - pip:
    - pytileproj
    - veranda
    - geopathfinder
    - geographiclib
