name: equi7grid_env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - numba
  - proj4
  - gdal
  - pyproj
  - cartopy
  - geographiclib
  - pip
  - pip:
    - pytileproj
    - veranda
