name: equi7grid_env
channels:
  - defaults
dependencies:
  - numpy
  - scipy
  - gdal
  - geopandas
  - cartopy
  - pyproj
  - pip
  - pip:
    - pytileproj
    - veranda
    - geopathfinder
    - geographiclib
    - pytest
    - pytest-cov
    - yapf
    - sphinx_rtd_theme
    - nbsphinx
